In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3826, 8517, 720, 7968],
 [3826, 8517, 720, 2488],
 [3826, 2313, 720, 8934],
 [9159, 6386, 6817, 4536, 9096],
 [9159, 6386, 6817, 4536, 9066],
 [3782, 3826, 967, 720, 1621],
 [7696, 7259, 4935, 4536]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3826 8517  720 7968]
 [   0    0    0    0 3826 8517  720 2488]
 [   0    0    0    0 3826 2313  720 8934]
 [   0    0    0 9159 6386 6817 4536 9096]
 [   0    0    0 9159 6386 6817 4536 9066]
 [   0    0    0 3782 3826  967  720 1621]
 [   0    0    0    0 7696 7259 4935 4536]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 216ms/step


array([[[ 0.03400663, -0.03494617, -0.04049873, -0.00039313,
         -0.03630006, -0.00376437, -0.04419987,  0.00616475,
          0.01884921,  0.02347643],
        [ 0.03400663, -0.03494617, -0.04049873, -0.00039313,
         -0.03630006, -0.00376437, -0.04419987,  0.00616475,
          0.01884921,  0.02347643],
        [ 0.03400663, -0.03494617, -0.04049873, -0.00039313,
         -0.03630006, -0.00376437, -0.04419987,  0.00616475,
          0.01884921,  0.02347643],
        [ 0.03400663, -0.03494617, -0.04049873, -0.00039313,
         -0.03630006, -0.00376437, -0.04419987,  0.00616475,
          0.01884921,  0.02347643],
        [ 0.03158088, -0.01162713, -0.01711529, -0.03627632,
         -0.04079925,  0.04565376, -0.03928233,  0.01045289,
         -0.0113494 , -0.02540734],
        [ 0.02691677,  0.02034897,  0.01541871, -0.04891736,
         -0.01098352,  0.02166302, -0.01304184, -0.01728619,
         -0.00543921,  0.03363109],
        [-0.02658471,  0.03885125,  0.01452924,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3826, 8517,  720, 7968])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 57ms/step


array([[ 0.03400663, -0.03494617, -0.04049873, -0.00039313, -0.03630006,
        -0.00376437, -0.04419987,  0.00616475,  0.01884921,  0.02347643],
       [ 0.03400663, -0.03494617, -0.04049873, -0.00039313, -0.03630006,
        -0.00376437, -0.04419987,  0.00616475,  0.01884921,  0.02347643],
       [ 0.03400663, -0.03494617, -0.04049873, -0.00039313, -0.03630006,
        -0.00376437, -0.04419987,  0.00616475,  0.01884921,  0.02347643],
       [ 0.03400663, -0.03494617, -0.04049873, -0.00039313, -0.03630006,
        -0.00376437, -0.04419987,  0.00616475,  0.01884921,  0.02347643],
       [ 0.03158088, -0.01162713, -0.01711529, -0.03627632, -0.04079925,
         0.04565376, -0.03928233,  0.01045289, -0.0113494 , -0.02540734],
       [ 0.02691677,  0.02034897,  0.01541871, -0.04891736, -0.01098352,
         0.02166302, -0.01304184, -0.01728619, -0.00543921,  0.03363109],
       [-0.02658471,  0.03885125,  0.01452924,  0.00757695, -0.02568374,
         0.01812382,  0.04588051, -0.00868469